### ISSUE TITLE
Unable to download Vanilla_UI_Plus_New_Vegas_8.73.7z

### ISSUE THREAD

**Issue by yainaya** [TDarkShadow/vivanewvegas-wabbajack#3]
```
137,49 - Hashing Remaining Archives
137,49 - Looking for files to hash
137,51 - Found 529 total files, 63 matching filesize
137,53 - Unable to download Vanilla_UI_Plus_New_Vegas_8.73.7z (ModDBDownloader+State|https://www.moddb.com/downloads/start/128019)
137,53 - Cannot continue, was unable to download one or more archives
137,53 - File hash check (-42) 1b1a32b75e749997cc69a5c1a04c4cafc14e29edb1548cf1dac8e108793f7772
137,57 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\AInstaller.cs:line 69
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 155
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass85_0.<<-ctor>b__75>d.MoveNext() in C:\actions-runner\_work\wabbajack\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 383
137,74 - File hash check (-42) 1b1a32b75e749997cc69a5c1a04c4cafc14e29edb1548cf1dac8e108793f7772
```

**Comment by TDarkShadow** [comment]
Fixed with commit https://github.com/TDarkShadow/vivanewvegas-wabbajack/commit/439c580ef1183a6b12a11927cda829c34a366bd7. Thank you for your report.
