### ISSUE TITLE
Vanilla-UI Plus update causes failed install

### ISSUE THREAD

**Issue by rburketaylor** [TDarkShadow/vivanewvegas-wabbajack#7]
When trying to install Vanilla UI fails because the author updated it today and the old version isn't available.

`44.94 - Unable to download Vanilla_UI_Plus_New_Vegas_8.86.7z (ModDBDownloader+State|https://www.moddb.com/downloads/start/128019?referer=https%3A%2F%2Fvivanewvegas.github.io%2F)
44.94 - Cannot continue, was unable to download one or more archives
44.94 - File hash check (-42) 5b20a760bdd448cb48642ea4603d0b7d2d06050d7400ebe1ba4b6ad87eb0b533
44.96 - Encountered error, can't continue - System.Exception: Cannot continue, was unable to download one or more archives
   at Wabbajack.Lib.AInstaller.Error(String msg) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\AInstaller.cs:line 71
   at Wabbajack.Lib.MO2Installer._Begin(CancellationToken cancel) in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\MO2Installer.cs:line 161
   at Wabbajack.Lib.ABatchProcessor.<Begin>b__66_0() in C:\Wabbajack\splitwork\wabbajack\Wabbajack.Lib\ABatchProcessor.cs:line 177
   at Wabbajack.MO2InstallerVM.<>c__DisplayClass31_0.<<Install>b__0>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 181
--- End of stack trace from previous location ---
   at Wabbajack.MO2InstallerVM.Install() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\MO2InstallerVM.cs:line 175
   at Wabbajack.InstallerVM.<>c__DisplayClass88_0.<<-ctor>b__78>d.MoveNext() in C:\Wabbajack\splitwork\wabbajack\Wabbajack\View Models\Installers\InstallerVM.cs:line 391
45.07 - File hash check (-42) 5b20a760bdd448cb48642ea4603d0b7d2d06050d7400ebe1ba4b6ad87eb0b533
`

**Comment by TDarkShadow** [comment]
Sorry for the late answer, but since 24 April, this is no longer an issue.
